spring:
  flyway:
    clean-on-validation-error: true
    enabled: true
    schemas: local
    placeholders:
      db.prefix: local
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_detail_database
    username: username
    password: password
  sql:
    init:
      mode: never
    jpa:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        properties:
          legacy_limit_handler: true
      show-sql: true
      properties:
        hibernate:
          default_schema: local
          format_sql: true
