runtime: java17
service: jit-backend
env: standard
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
