CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE ${db.prefix}.CUSTOMER
(
    CUSTOMER_ID UUID DEFAULT uuid_generate_v4 () NOT NULL,
    FIRST_NAME VARCHAR NULL,
    LAST_NAME VARCHAR NULL,
    EMAIL VARCHAR NULL,
    PHONE VARCHAR NULL,
    STREET_ADDRESS VARCHAR NULL,
    CITY VARCHAR NULL,
    ZIP VARCHAR NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ${db.prefix}.SERVICE_TYPE
(
    SERVICE_TYPE_ID SMALLSERIAL,
    SERVICE_TYPE VARCHAR NOT NULL,
    PRIMARY KEY (SERVICE_TYPE_ID)
);

CREATE TABLE ${db.prefix}.VEHICLE
(
    VEHICLE_ID UUID DEFAULT uuid_generate_v4 () NOT NULL,
    CUSTOMER_ID UUID NOT NULL,
    SERVICE_TYPE_ID INT NOT NULL,
    MAKE VARCHAR NULL,
    MODEL VARCHAR NULL,
    YEAR INT NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL,
    PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT fk_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES ${db.prefix}.CUSTOMER(CUSTOMER_ID),
    CONSTRAINT fk_service_type FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES ${db.prefix}.SERVICE_TYPE(SERVICE_TYPE_ID)
);

CREATE TABLE ${db.prefix}.BOOKING
(
    BOOKING_NUMBER UUID DEFAULT uuid_generate_v4 () NOT NULL,
    CUSTOMER_ID UUID NULL,
    VEHICLE_ID UUID NULL,
    DATE_OF_SERVICE TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL,
    PRIMARY KEY (BOOKING_NUMBER),
    CONSTRAINT fk_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES ${db.prefix}.CUSTOMER(CUSTOMER_ID),
    CONSTRAINT fk_vehicle FOREIGN KEY (VEHICLE_ID) REFERENCES ${db.prefix}.VEHICLE(VEHICLE_ID)
);

INSERT INTO ${db.prefix}.SERVICE_TYPE (SERVICE_TYPE)
VALUES ('NA'), ('J.I.T WASH & WAX (EXTERIOR ONLY)'), ('J.I.T BASIC PACKAGE (INTERIOR/EXTERIOR)'),
       ('J.I.T PREMIUM PACKAGE (INTERIOR/EXTERIOR)'), ('J.I.T PLATINUM PACKAGE (INTERIOR/EXTERIOR)'),
       ('J.I.T INTERIOR DETAIL PACKAGE'), ('J.I.T PET PACKAGE (INTERIOR ONLY)'),
       ('J.I.T LIGHT SWIRL REMOVER + WAX PACKAGE (EXTERIOR)'), ('PET HAIR REMOVAL'), ('ODOR REMOVAL'),
       ('J.I.T CUSTOMIZED PACKAGE');
