CREATE TABLE ${db.prefix}.USER_ROLES (
    USER_ENTITY_ID UUID NOT NULL,
    ROLES_ID UUID NOT NULL,
    PRIMARY KEY (USER_ENTITY_ID, ROLES_ID),
    FOREIGN KEY (USER_ENTITY_ID) REFERENCES ${db.prefix}.USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLES_ID) REFERENCES ${db.prefix}.ROLE(ID) ON DELETE CASCADE
);
